### ISSUE TITLE
Hostnamectl plugin causes systemd Hostname service to restart at every ohai/chef-client run

### ISSUE THREAD

**Issue by sterago** [chef/ohai#962] opened 2017-03-08 15:00 UTC
## Description

The hostnamectl plugin runs the `hostnamectl` command to determine the value of certain attributes. However, this command triggers the (re)start of systemd's Hostname service.

## Ohai Version

8.23.0

## Platform Version

Debian GNU/Linux 8.7 (jessie)

To reproduce, one can run ohai (or simply `hostnamectl`) on a Jessie machine and inspect the content of the syslog.

Here is a sample of such output:

```
2017-03-08T15:48:26.010543+01:00 demo dbus[465]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
2017-03-08T15:48:26.011796+01:00 demo systemd[1]: Starting Hostname Service...
2017-03-08T15:48:26.023149+01:00 demo systemd-hostnamed[22099]: Warning: nss-myhostname is not installed. Changing the local hostname might make it unresolveable. Please install nss-myhostname!
2017-03-08T15:48:26.023633+01:00 demo dbus[465]: [system] Successfully activated service 'org.freedesktop.hostname1'
2017-03-08T15:48:26.023872+01:00 demo systemd[1]: Started Hostname Service.
```

**Comment by tas50** [comment] 2020-11-17 01:15
Closing this out since the systemd folks seem to think this is the expected behavior. If the spam is too much for you then you can disable this plugin via your client.rb config.

**Closed by tas50** 2020-11-17 01:15 UTC
