### ISSUE TITLE
Ohai doesn't distinguish between Amazon Machine Linux v1 and v2

### ISSUE THREAD

**Issue by tomharvey** [chef/ohai#1218] opened 2018-07-06 23:01 UTC
## Description
Following chef 13, in accordance with https://docs.chef.io/deprecations_ohai_amazon_linux.html Ohai will report the below:
```
$ ohai | grep platform
[2018-07-06T22:47:18+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
  "platform": "amazon",
  "platform_version": null,
  "platform_family": "amazon",
```
regardless of the version of amazon linux.

The platform_version should be explicit, certainly now that there are 2 versions.

Amazon Linux 2 behaves far more like RHEL7 - so, version could report `7` for v2 or it could actually represent the version of amazon linux and report `2`

## Ohai Version

14.2.0

## Platform Version

Amazon Machine Linux 2

## Ohai Output
As in the description.

**Comment by tas50** [comment] 2018-07-06 23:08
Dupe of #1207 which was fixed by #1214 and goes out next week.

**Closed by tas50** 2018-07-06 23:08 UTC
