### ISSUE TITLE
dmi.rb:ID_TO_CAPTURE array is frozen?

### ISSUE THREAD

**Issue by kevinleiyan** [chef/ohai#1407] opened 2019-10-11 01:41 UTC
## Description
ID_TO_CAPTURE array is frozen
Briefly describe the issue

## Ohai Version
15.3.1
## Platform Version
centos 6/7
## Ohai Output
I want to add "17" (memory_devices) into ID_TO_CAPTURE. 
but I get ' `<<': can't modify frozen array'

the frozen ID_TO_CAPTURE array is by design?

**Comment by lamont-granquist** [comment] 2019-11-05 02:58
that's by design, `Ohai.config[:additional_dmi_ids]` is the way to add more:

https://github.com/chef/ohai/blob/f5eed7c04a407b5ee138125000860b29325e1f21/lib/ohai/common/dmi.rb#L84

closing as not a bug.

**Closed by lamont-granquist** 2019-11-05 02:58 UTC
